sudo: required
services:
    - docker

before_install:
    - docker build -t osmangurten/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true osmangurten/docker-react npm run test
    