sudo: required
services:
    - docker

before_install:
    - docker build -t osmangurten/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true osmangurten/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-us-east-1-131194193142"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY